version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "test/dummy/Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            cd test/dummy
            gem install bundler -v 2.0.1
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "test/dummy/Gemfile.lock" }}

      # - run: bundle exec rake db:create
      # - run: bundle exec rake db:schema:load


      - run:
          name: run tests
          command: |
            cd test/dummy
            bundle exec rspec spec
